add_executable(hik_camera_profile_control_test profile_control_test.cpp)
target_include_directories(
  hik_camera_profile_control_test PRIVATE ${CMAKE_CURRENT_LIST_DIR}/..
)
target_compile_features(hik_camera_profile_control_test PRIVATE cxx_std_20)
add_test(NAME hik_camera_profile_control_test COMMAND hik_camera_profile_control_test)

add_executable(hik_camera_runtime_param_test runtime_param_test.cpp)
target_link_libraries(hik_camera_runtime_param_test PRIVATE xr)
target_compile_features(hik_camera_runtime_param_test PRIVATE cxx_std_20)
add_test(NAME hik_camera_runtime_param_test COMMAND hik_camera_runtime_param_test)
