add_executable(hik_camera_test hik_camera_test.cpp)
target_include_directories(hik_camera_test PRIVATE ${CMAKE_CURRENT_LIST_DIR}/..)
target_link_libraries(hik_camera_test PRIVATE xr HikMVS::MvCameraControl)
target_compile_features(hik_camera_test PRIVATE cxx_std_20)
add_test(NAME hik_camera_test COMMAND hik_camera_test)
